version: '3'

services:
  db:
    image: mysql:5.7.33
    env_file: 
      - .env 
    environment: 
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - mysql_cache:/var/lib/mysql
    networks:
      - internal 
  web:
    image: sonsn/circel-ci-rails:1.1
    env_file: 
      - .env
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on: 
      - db
    networks:
      - internal
    tty: true
    stdin_open: true

volumes:
  mysql_cache:
  bundle_cache:
networks:
  internal: 
    driver: bridge
  